# Generated by Django 4.2.1 on 2025-04-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
