# Generated by Django 4.2.1 on 2025-04-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizzle', '0002_remove_customuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefprofiles',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='id',
        ),
        migrations.AlterField(
            model_name='chefprofiles',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'chef'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
